query ProductCategoryQuery($input: IIoRestorecommerceResourcebaseReadRequest!) {
  catalog {
    product_category {
      Read(input: $input) {
        details {
          items {
            payload {
              id
              name
              description
              parent {
                parentId
              }
              image {
                filename
                caption
                url
              }
            }
            status {
              code
              message
            }
          }
          totalCount
          operationStatus {
            code
            message
          }
        }
      }
    }
  }
}
