query ProductsQuery($input: IIoRestorecommerceResourcebaseReadRequest!) {
  catalog {
    product {
      Read(input: $input) {
        details {
          items {
            payload {
              id
              product {
                name
                description
                categoryId
                category {
                  id
                  name
                  parent {
                    parentId
                  }
                }
                physical {
                  variants {
                    id
                    name
                    description
                    price {
                      regularPrice
                      sale
                      salePrice
                    }
                    stockKeepingUnit
                    stockLevel
                    parentVariantId
                    package {
                      rotatable
                      sizeInCm {
                        height
                        length
                        width
                      }
                      weightInKg
                    }
                    images {
                      filename
                      url
                      caption
                    }
                    properties {
                      id
                      value
                    }
                  }
                }
              }
              meta {
                owners {
                  id
                  value
                  attributes {
                    id
                    value
                  }
                }
              }
            }
            status {
              code
              message
            }
          }
          totalCount
          operationStatus {
            code
            message
          }
        }
      }
    }
  }
}
